### ISSUE TITLE
Please could you port this to .netstandard2.0?

### ISSUE THREAD

**Issue by las-nsc** [pmotakef/Fieldtree2D#2]
This seems to be the only nuget with a bottom-up quadtree, so it would be nice to see it be more compatible.

Thanks.

Also, I think you meant `Bottom` rather than `Buttom`.

**Comment by pmotakef** [comment]
Thanks a lot for your comment. Silly me for the typo. Thanks for catching it. 

Regarding .netstandard, I haven't worked with that, but since I wrote it purely in C# I thought it should be compatible with any .net framework.  I will try to look into .netstandard and see how easy it is to make the jump.

By the way, all help is appreciated :)

Thanks

**Comment by pmotakef** [comment]
The package is now ported to .Net 6.0
